import { goldenHourTemplate } from "./v1.js";

export const GOLDEN_HOUR_V2_TEMPLATE_VERSION_ID = "40000000-0000-4000-8000-000000000007";

export const goldenHourTemplateV2 = {
  listing: {
    ...goldenHourTemplate.listing,
    date: "August 14, 2027 · Quezon City",
    description:
      "A midnight ballroom program with brass geometry, an XVIII medallion, and space for the traditions and people of a debut.",
  },
  celebrantPronoun: "she",
  editorKey: "section-document-v1",
  templateVersionId: GOLDEN_HOUR_V2_TEMPLATE_VERSION_ID,
  supersedesTemplateVersionId: goldenHourTemplate.templateVersionId,
  version: 2,
  qualityStatus: "production",
  rendererKey: "golden-hour-v2",
  schemaVersion: 1,
  allowedSections: [
    "hero",
    "message",
    "countdown",
    "event-details",
    "participants",
    "schedule",
    "attire",
    "gallery",
    "guidance",
    "rsvp",
  ],
  defaultDocument: {
    schemaVersion: 1,
    templateVersionId: GOLDEN_HOUR_V2_TEMPLATE_VERSION_ID,
    locale: "en-PH",
    eventTimezone: "Asia/Manila",
    theme: {
      colors: {
        background: "#211a23",
        surface: "#302631",
        text: "#f8edda",
        accent: "#d3ad60",
        accentContrast: "#211a23",
      },
      typography: {
        headingFontId: "fraunces",
        bodyFontId: "instrument-sans",
      },
      spacingScale: "comfortable",
    },
    opening: {
      preset: "ribbon-envelope-letter",
      motionStyle: "cinematic",
      recipientMode: "personalized",
      fallbackRecipientText: "Our honored guest",
    },
    sections: [
      {
        id: "52000000-0000-4000-8000-000000000001",
        type: "hero",
        visible: true,
        animationPreset: "scale-in",
        props: {
          eyebrow: "An evening in gold",
          title: "Sam turns XVIII",
          subtitle: "Join us for her milestone entrance and a night shaped by family and friends",
          dateLabel: "Saturday, August 14, 2027",
        },
      },
      {
        id: "52000000-0000-4000-8000-000000000002",
        type: "message",
        visible: true,
        animationPreset: "fade-up",
        props: {
          heading: "Eighteen years, one bright beginning",
          body: "With gratitude for every person who helped her grow, our family invites you to celebrate Samantha’s eighteenth birthday.",
          signature: {
            lead: "With love,",
            names: ["Andrea and Marco Villareal"],
          },
        },
      },
      {
        id: "52000000-0000-4000-8000-000000000003",
        type: "countdown",
        visible: true,
        animationPreset: "fade-in",
        props: {
          heading: "Until the doors open",
          target: "2027-08-14T18:00:00+08:00",
          dateLabel: "Saturday, August 14, 2027 at 6:00 PM",
        },
      },
      {
        id: "52000000-0000-4000-8000-000000000004",
        type: "event-details",
        visible: true,
        animationPreset: "fade-up",
        props: {
          heading: "The evening",
          events: [
            {
              label: "Debut celebration",
              startAt: "2027-08-14T18:00:00+08:00",
              dateLabel: "6:00 PM",
              venueName: "The Meridian Ballroom",
              address: "Quezon City, Metro Manila, Philippines",
              mapUrl: "https://maps.google.com/",
              arrivalNote: "Doors open at 5:30 PM. Please be seated before the grand entrance.",
            },
          ],
        },
      },
      {
        id: "52000000-0000-4000-8000-000000000005",
        type: "participants",
        visible: true,
        animationPreset: "stagger-children",
        props: {
          heading: "The people in her eighteen",
          groups: [
            {
              label: "18 roses",
              names: [
                "Marco Villareal",
                "Lucas Reyes",
                "Mateo Cruz",
                "Gabriel Santos",
                "Paolo Lim",
                "Andre Flores",
                "Enzo Garcia",
                "Nico Mendoza",
                "Daniel Yu",
                "Luis Tan",
                "Rafael Co",
                "Miguel Sy",
                "Adrian Ramos",
                "Joaquin de Leon",
                "Carlo Bautista",
                "Theo Navarro",
                "Elijah Castillo",
                "Sebastian Ong",
              ],
            },
            {
              label: "18 candles",
              names: [
                "Andrea Villareal",
                "Alyssa Reyes",
                "Bianca Cruz",
                "Camille Santos",
                "Dani Lim",
                "Elena Flores",
                "Frances Garcia",
                "Gabriela Mendoza",
                "Hannah Yu",
                "Isabel Tan",
                "Julia Co",
                "Kara Sy",
                "Lia Ramos",
                "Mia de Leon",
                "Nina Bautista",
                "Olivia Navarro",
                "Patricia Castillo",
                "Rina Ong",
              ],
            },
            {
              label: "18 treasures",
              names: [
                "Amelia Reyes",
                "Carmen Cruz",
                "Elena Santos",
                "Lourdes Lim",
                "Marissa Flores",
                "Teresa Garcia",
              ],
            },
          ],
        },
      },
      {
        id: "52000000-0000-4000-8000-000000000006",
        type: "schedule",
        visible: true,
        animationPreset: "fade-up",
        props: {
          heading: "Program",
          items: [
            { timeLabel: "5:30 PM", title: "Doors open" },
            { timeLabel: "6:00 PM", title: "Grand entrance" },
            { timeLabel: "6:20 PM", title: "Dinner" },
            { timeLabel: "7:30 PM", title: "18 roses" },
            { timeLabel: "8:05 PM", title: "18 candles" },
            { timeLabel: "8:40 PM", title: "18 treasures" },
            { timeLabel: "9:10 PM", title: "A message from Sam" },
            { timeLabel: "9:30 PM", title: "Dancing" },
          ],
        },
      },
      {
        id: "52000000-0000-4000-8000-000000000007",
        type: "attire",
        visible: true,
        animationPreset: "fade-up",
        props: {
          heading: "Formal evening attire",
          description:
            "Long dresses, suits, Barong Tagalog, and polished separates are welcome. Please leave white and gold for the debutante.",
          colors: [
            { label: "Aubergine", value: "#4b3148" },
            { label: "Midnight", value: "#211a23" },
            { label: "Dusty rose", value: "#b9878e" },
          ],
        },
      },
      {
        id: "52000000-0000-4000-8000-000000000008",
        type: "gallery",
        visible: false,
        animationPreset: "fade-up",
        props: {
          heading: "Eighteen chapters",
          description: "Photographs from the years that led to this evening.",
          images: [],
        },
      },
      {
        id: "52000000-0000-4000-8000-000000000009",
        type: "guidance",
        visible: true,
        animationPreset: "fade-up",
        props: {
          heading: "A note for the evening",
          items: [
            "Please arrive before the grand entrance so the program can begin on time.",
            "The ballroom is fully air-conditioned; a light wrap may be useful.",
            "Share your photographs with #SamAtXVIII.",
          ],
        },
      },
      {
        id: "52000000-0000-4000-8000-000000000010",
        type: "rsvp",
        visible: true,
        animationPreset: "fade-up",
        props: {
          heading: "Reserve your evening",
          message: "Please respond on your personal invitation by July 24, 2027.",
          deadline: "2027-07-24T23:59:59+08:00",
        },
      },
    ],
    assets: [],
  },
} as const;
